from re import A
print(bool(True))
print(bool(A))
print(bool(123))
print(bool("Hello Guys!"))
print(bool(('tupples', 97.89, 574)))
print(bool(['Keyboard', 'Mouse']))
print(bool({'qwerty', 'abcd'}))
print() # giving a line gap
print(bool(False))
print(bool(None))
print(bool(0))
print(bool(""))
print(bool(()))
print(bool([]))
print(bool({}))
